version: '3.8'

#kas seda on vaja?
# x-common-variables: &common-variables
#   MYSQL_DATABASE: watermeter
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
#mysql setup
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      # <<: *common-variables
      MYSQL_DATABASE: watermeter
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

#nginx setup
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

#services setup
  api:
    build:
      dockerfile: server.Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      # <<: *common-variables
      # MYSQL_DATABASE: watermeter
      # MYSQL_USER: MYSQL_USER
      # MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_HOST_IP: mysql_db

#client setup
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: client.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

#adminer setup
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db