version: '3.8'

services:
#mysql setup
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./database/createDBUser.sql:/docker-entrypoint-initdb.d/createDBUser.sql"
      - "./database/WaterMeterTablesCreationScript.sql:/docker-entrypoint-initdb.d/WaterMeterTablesCreationScript.sql"
      - "./database/createData.sql:/docker-entrypoint-initdb.d/createData.sql"
      - ./database/db_container_volume:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

#server setup
  api:
    build:
      dockerfile: server.Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
      - .env:/app/.env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOST_IP: "${MYSQL_HOST_IP}"
    ports:
      - 3050:3000

#client setup
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: client.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "80:5000"